DEBUG tests/ex1_tests.c:38: ----- RUNNING: ./tests/ex1_tests
DEBUG tests/ex1_tests.c:33: 
----- test_ex1
[ERROR] (tests/ex1_tests.c:13: errno: None) Your function did not return the expected answer for input {4, 4}
